language: rust
sudo: false


matrix:
  include:
    - os: linux
      rust: nightly
      env: FEATURES="unstable"
    - os: linux
      rust: nightly
      env: FEATURES="unstable force-inprocess"
    - os: linux
      rust: nightly
      env: FEATURES="unstable memfd"
    - os: osx
      rust: nightly
      env: FEATURES="unstable"
    - os: osx
      rust: nightly
      env: FEATURES="unstable force-inprocess"

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
