
language: rust
sudo: false

rust:
  - nightly

os:
  - linux
  - osx

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES="unstable"
    - FEATURES="unstable force-inprocess"

matrix:
  include:
    - os: linux
      env: FEATURES="unstable memfd"

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
